# Melhor configuração medida:
#   API_WORKERS=2
#   api1/api2: 0.47 CPU cada
#   lb: 0.06 CPU
# Total: 1.00 CPU
#
# Observação:
# A imagem atual não tem /app/healthcheck, então não use healthcheck baseado nisso.

x-api: &api-common
  image: ghcr.io/sl4ureano/rinha2026:herbert-richers
  pull_policy: always
  command: ["/app/api"]
  volumes:
    - sockets:/tmp/sockets
  ulimits:
    nofile:
      soft: 65535
      hard: 65535
  deploy:
    resources:
      limits:
        cpus: "0.47"
        memory: 169M
  logging:
    driver: none

services:
  api1:
    <<: *api-common
    cpuset: "0"
    environment:
      CTRL_SOCK: "/tmp/sockets/api1.sock"
      INDEX_PATH: "/app/data/index.bin"
      API_WORKERS: "2"
    network_mode: "none"

  api2:
    <<: *api-common
    cpuset: "2"
    environment:
      CTRL_SOCK: "/tmp/sockets/api2.sock"
      INDEX_PATH: "/app/data/index.bin"
      API_WORKERS: "2"
    network_mode: "none"

  lb:
    image: ghcr.io/sl4ureano/rinha2026:herbert-richers
    pull_policy: always
    command: ["/app/lb"]
    cpuset: "1,3"
    environment:
      FD_PASS: "1"
      API1_SOCKET: "/tmp/sockets/api1.sock"
      API2_SOCKET: "/tmp/sockets/api2.sock"
    ports:
      - "9999:9999"
    depends_on:
      - api1
